#!/usr/bin/ruby

require 'lib/util.rb'
require 'lib/nginxctl.rb'
require 'lib/nodectl.rb'
require 'lib/neo4jctl.rb'

def main
    ctls = [NginxCtl.new, NodeCtl.new, Neo4jCtl.new]

    case ARGV[0]
        when "start" then ctls.map{|ctl| ctl.start}
        when "stop" then ctls.map {|ctl| ctl.stop}
        when "restart" then ctls.map {|ctl| ctl.restart}
    end
end

# Kick off the script.
main
